server:
  port: 9291
spring:
  application:
    name: market-server
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: root
      username: root
      url: jdbc:mysql://59.110.94.218:3306/supermarket_manager?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      dbcp2:
        maxActive: 80 # 最大活动连接
        initialSize: 10 # 初始化连接
        maxIdle: 60 # 最大空闲连接
        minIdle: 10 # 最小空闲连接
        maxWait: 3000 # 从池中取连接的最大等待时间，单位ms
        validationQuery: select 1 # 验证使用的SQL语句
        testWhileIdle: true # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除
        testOnBorrow: false # 借出连接时不要测试，否则很影响性能
        timeBetweenEvictionRunsMillis: 30000 # 每30秒运行一次空闲连接回收器
        minEvictableIdleTimeMillis: 1800000 # 池中的连接空闲30分钟后被回收
        numTestsPerEvictionRun: 3 #在每次空闲连接回收器线程(如果有)运行时检查的连接数量
        removeAbandoned: true #连接泄漏回收参数，当可用连接数少于3个时才执行
        removeAbandonedTimeout: 180 # 连接泄漏回收参数，180秒，泄露的连接可以被删除的超时值
  redis:
    host: localhost
    port: 6379
    password:
  mvc:
    async:
      request-timeout: 20000
mybatis-plus:
  mapper-locations: classpath:com/rabbiter/market/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    cn.dingli.market.mapper: debug

