server:
  port: 9292
spring:
  application:
    name: market-server
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: root
      username: root
      url: jdbc:mysql://59.110.94.218:3306/supermarket_manager?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
  redis:
    host: localhost
    port: 6379
    password:
  mvc:
    async:
      request-timeout: 20000
mybatis-plus:
  mapper-locations: classpath:com/rabbiter/market/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    cn.dingli.market.mapper: debug

